### ISSUE TITLE
Add ReadMe File

### ISSUE THREAD

**Issue by victor-kironde** [philip-bbaale/Elevator#1]
- Explain the problem in-depth
- Solution in-depth, 
- How to Setup, Run, Test
- Known issues/Blockers

**Comment by philip-bbaale** [comment]
Done ✅

**Comment by victor-kironde** [comment]
> @philip-bbaale The Readme does not include this information
> 
> **Solution in-depth,** There is no explanation of how the elevator works e.g if it uses **First Come First Serve** algorithm or otherwise
> 
> **Known issues/Blockers** There is no mention on the elevator's limitations, bugs, or blockers

@philip-bbaale address this
